name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: rockylinux:8.8

    steps:
    - uses: actions/checkout@v3
    - name: configure1
      run: dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    - name: configure2
      run: dnf install -y bzip2 rpm-build wget pgdg-srpm-macros
    - name: configure3
      run: dnf --enablerepo=powertools install -y perl-IPC-Run
    - name: configure4
      run: dnf -qy module disable postgresql
    - name: configure5
      run: dnf install -y postgresql${PG_MAJOR_VERSION}-devel postgresql${PG_MAJOR_VERSION}-server pgdg-srpm-macros
    - name: configure6
      run:  dnf -y install sqlite-devel
    - name: make check
      run: make check USE_PGXS=1 
